config/routes.rb
Rails.application.routes.draw do
  resources :usershops
  resources :sectors
  get 'orderlogdayshop', to: 'orderlogs#indexdayshop'
  resources :orderlogs, :only => [:create, :index]
  resources :recipes
  resources :ingredients
  post 'locktoday', to: 'lockdays#locktoday'
  resources :lockdays, :only => [:index, :new, :create, :destroy]
  get 'reports/baker'
  get 'reports/deliver'

  get 'ordersedit', to: 'orders#indexedit'
  post 'orders/:id', to: 'orders#update'
  get 'ordersproductshops', to: 'orders#productshop'
  get 'ordersbakers', to: 'orders#bakers'
  get 'ordersbakerdoes', to: 'orders#bakerdoes'
  get 'ordersdelivery', to: 'orders#delivery'
  get 'ordersdeliverypdf', to: 'orders#deliverypdf'
  get 'downloadorders', to: 'orders#downloadorders'
  #get 'ordersbakers/:day', to: 'orders#bakers'
  #get 'ordersdelivery/:day', to: 'orders#delivery'
  resources :orders
  #get 'sessions/new'
  #get 'sessions/create'
  #get 'sessions/destroy'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end
  
  post 'userdayshop(/:id)', to: 'users#updatedayshop'
  patch 'userdayshop(/:id)', to: 'users#updatedayshop'
  get 'userdayshop', to: 'users#editdayshop'
  resources :users
  resources :shops,  :except => [:destroy]
  get 'displayproducts', to: 'products#display'
  resources :products, :except => [:destroy]
  
  root 'orders#indexedit'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_destroy :ensure_not_referenced_by_any_order_or_orderlog
  
  validates :email, uniqueness: true
  
  has_many :usershops, dependent: :destroy
  has_many :shops, through: :usershops
  has_many :lockdays
  has_many :orders
  has_many :orderlogs
  


    private
        # ensure that there are no orders referencing this user
        def ensure_not_referenced_by_any_order_or_orderlog
            unless orders.empty?
                errors.add(:base, 'Cannot destroy - orders present for this user')
                throw :abort
            end
            unless orderlogs.empty?
                errors.add(:base, 'Cannot destroy - orderlog entries present for this user')
                throw :abort
            end            
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    get_shop_options
    set_role_options
    #@role_options = ["shop", "baker", "owner", "root", "none"]
    #@shop_options = Shop.all.order(:name).map{ |u| [u.name] }
    #logger.debug "@shop_options: " + @shop_optons.inspect
    #logger.debug "@role_options: " + @role_optons.inspect
  end

  # GET /users/1/edit
  def edit
    get_shop_options
    ###@shop_options = Shop.all.order(:name).map{ |u| [u.name] }
    #logger.debug "@shop_options: " + @shop_optons.inspect
    set_role_options
    #@role_options = ["shop", "baker", "owner", "root", "none"]
    #logger.debug "@role_options: " + @role_optons.inspect
  end

  # GET /users/1/editdayshop
  def editdayshop
    unless session[:user_id].nil?  # check that we are logged in
      @user = User.where(id: session[:user_id])
      ###@shop_list = Shop.find_by_sql [ "
      ###  select u.id as user_id, u.name, s.name, s.id as shop_id
      ###  FROM shops AS s
      ###  JOIN usershops AS x ON x.shop_id = s.id
      ###  JOIN users AS u ON u.id =x.user_id
      ###  WHERE user_id = ?
      ###", session[:user_id] ]
      ###@shop_options = @shop_list.map{ |u| [u.name]}
      #logger.debug "@shop_options: " + @shop_options.inspect
      get_shop_options
    else
      redirect_to users_url, notice: 'User is not logged in!!!'
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        logger.debug "users controller - update => update successful"
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        logger.debug "users controller - update => update failed"
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1/updatedayshop
  # PATCH/PUT /users/1.json
  def updatedayshop
    @user = User.find(user_params[:id])
    #logger.debug "@user:" + @user.inspect

    @myparams = user_params
    #logger.debug "@myparams:" + @myparams.inspect

    @currentparams = @user.attributes
    #logger.debug "@currentparams:" + @currentparams.inspect

    @myshop = user_params[:shop]
    #logger.debug "@myshop:" + @myshop.inspect

    #@myday =Date.new @myparams["day(1i)"].to_i, @myparams["day(2i)"].to_i, @myparams["day(3i)"].to_i
    @myday = @myparams["day"]
    #logger.debug "@myparams day:" + @myparams["day"]
    #logger.debug "@myday:" + @myday.inspect
    
    if @user.shop != @myshop
      #logger.debug "shop has changed"
      unless @myshop.nil?
        #logger.debug "shop has valid value" + @myshop.inspect
        @user.update_attribute(:shop, @myshop)
      end
    end
    
    if @user.day != @myday
      #logger.debug "day has changed"
      unless @myday.nil?
        #logger.debug "day has valid value" + @myday.inspect
        @user.update_attribute(:day, @myday)
      end
    end
    #logger.debug "@user:" + @user.inspect

    respond_to do |format|
      if @user.save
        unless session[:user_id].nil?  # user is logged in
          # update matching session parameters
          session[:user_day] = @myday unless @myday.nil?
          unless @myshop.nil?
            @shop = Shop.find_by(name: @myshop)
            logger.debug "@shop: " + @shop.inspect
            session[:user_shop] = @myshop
            session[:user_shop_id] = @shop.id
          end
        end
        logger.debug "users controller - update => update successful"
        format.html { redirect_to ordersedit_path }
        format.json { render :show, status: :ok, location: @user }
        
      else
        logger.debug "users controller - update => update failed"
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /users/1
  # DELETE /users/1.json
  # Never want to destroy users as they linked in the orders audit trail.
  # To disable a user, set the role to "none"
  def destroy
    respond_to do |format|
      if @user.destroy
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      else
        if @user.errors.any?
          @notice_message = "prohibited this user from being destroyed"
          @user.errors.full_messages.each do |message|
            @notice_message += ": " + message
          end
        end
        format.html { redirect_to users_url, notice: @notice_message }
        format.json { head :no_content }      
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:id, :name, :email, :password, :password_confirmation, :role, :day, :shop,
        :shop_ids => []
      )
    end
    
    # consistent generatoion of the role options across the actions
    def set_role_options
      @role_options = ["shop", "baker", "owner", "root", "none"]
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= f.label :role %>
    <%= f.select :role, @role_options %>
  </div>
  <% logger.debug "user: " + user.inspect %>
  <% if ["shop", nil].include? user.role %>
    <div class="managed_shops" >
  <% else %>
    <div class="managed_shops, hideme" >
  <% end %>
      <br>
      This shop selection field is for linking the user to shops allowing management of their orders<br>
      <b> Hold down "control" key to select multiple shops. </b><br>
      <%= f.select :shop_ids, Shop.all.collect{|x|[x.name, x.id]}, {}, :multiple => true %>
      <p>
    </div>
    
  <div class="field">
    <%= f.label :day %>
    <%= f.date_select :day %>
  </div>

  <div class="field">
    <%= f.label :shop %>
    <%= f.select :shop, @shop_options %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/editdayshop.html.erb
<h1>Editing Shop and Day for User - editdayshop</h1>

<% user = @user.first %>
<%= form_for(user, :url => userdayshop_path, method: :patch) do |f| %>

  <div class="field">
    <%= f.text_field :id, hidden: true %>
  </div>
  
  <div class="intro"></div>
   For <%= user.name %>, change the day and/or shop that you wish to work on.
  </div>
  
  <div class="field">
    <%= f.label :day %>
    <% if false %>
      </div><%= f.date_select :day %>
    <% else %>
      <input type="date" name="user[day]" value="<%= user.day %>">
    <% end %>
  </div>

  <div class="field">
    <%= f.label :shop %>
    <%= f.select :shop, @shop_options %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', ordersedit_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
      <th>Managed Shops</th>
      <th>Day</th>
      <th>Shop</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td>
          <% if user.role == "shop" %>
            <% user.shops.each do |shop| %>
              <%= shop.name %><br>
            <% end %>
          <% end %>
        </td>
        <td><%= user.day %></td>
        <td><%= user.shop %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= link_to 'Update your day/shop', userdayshop_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<p>
<strong>Managed Shops</strong >
  <br>This user can manage orders for these shops
  <br>Note: only applies to users with role "shop"<br>
  
  <% @user.shops.each do |shop| %>
    => <%= shop.name %><br>
  <% end %>
</p>
   
<p>
  <strong>Day:</strong>
  <%= @user.day %>
</p>

<p>
  <strong>Shop:</strong>
  <%= @user.shop %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>