config/routes.rb
Rails.application.routes.draw do
  resources :usershops
  resources :sectors
  get 'orderlogdayshop', to: 'orderlogs#indexdayshop'
  resources :orderlogs, :only => [:create, :index]
  resources :recipes
  resources :ingredients
  post 'locktoday', to: 'lockdays#locktoday'
  resources :lockdays, :only => [:index, :new, :create, :destroy]
  get 'reports/baker'
  get 'reports/deliver'

  get 'ordersedit', to: 'orders#indexedit'
  post 'orders/:id', to: 'orders#update'
  get 'ordersproductshops', to: 'orders#productshop'
  get 'ordersbakers', to: 'orders#bakers'
  get 'ordersbakerdoes', to: 'orders#bakerdoes'
  get 'ordersdelivery', to: 'orders#delivery'
  get 'ordersdeliverypdf', to: 'orders#deliverypdf'
  get 'downloadorders', to: 'orders#downloadorders'
  #get 'ordersbakers/:day', to: 'orders#bakers'
  #get 'ordersdelivery/:day', to: 'orders#delivery'
  resources :orders
  #get 'sessions/new'
  #get 'sessions/create'
  #get 'sessions/destroy'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end
  
  post 'userdayshop(/:id)', to: 'users#updatedayshop'
  patch 'userdayshop(/:id)', to: 'users#updatedayshop'
  get 'userdayshop', to: 'users#editdayshop'
  resources :users
  resources :shops,  :except => [:destroy]
  get 'displayproducts', to: 'products#display'
  resources :products, :except => [:destroy]
  
  root 'orders#indexedit'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    validates :item, :unit, presence: true
    validates :item, uniqueness: true
    
    has_many :recipes
    has_many :products, through: :recipes
    
    before_destroy :ensure_not_referenced_by_any_recipe

    private
        # ensure that there are no recipes referencing this ingredient
        def ensure_not_referenced_by_any_recipe
            unless recipes.empty?
                errors.add(:base, ' - recipes present for this ingredient')
                throw :abort
            end
        end
end

app/models/lockday.rb
class Lockday < ApplicationRecord
    validates :day, uniqueness: true
    
    belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :shop
  belongs_to :user
  
  def self.dayshop(day, shop_id)
    where("day = ? and shop_id = ?", day, shop_id)
  end
  
end

app/models/orderlog.rb
class Orderlog < ApplicationRecord
    belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
    validates :title, presence: true
    validates :price, numericality: {greater_than_or_equal_to: 0.01}
    validates :title, uniqueness: true
    
    has_many :orders
    has_many :shops, through: :orders
    has_many :recipes
    has_many :ingredients, through: :recipes
    belongs_to :sector
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :product
  belongs_to :ingredient
end

app/models/sector.rb
class Sector < ApplicationRecord
    has_many :products 
    before_destroy :ensure_not_referenced_by_any_product

    private
        # ensure that there are no products referencing this sector
        def ensure_not_referenced_by_any_product
            unless products.empty?
                errors.add(:base, 'Cannot destroy - products present for this sector')
                throw :abort
            end
        end
end

app/models/shop.rb
class Shop < ApplicationRecord
    validates :name, :contact, :phone, :email, presence: true
    validates :name, uniqueness: true
    
    has_many :orders
    has_many :products, through: :orders
    
    has_many :usershops
    has_many :users, through: :usershops
    
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_destroy :ensure_not_referenced_by_any_order_or_orderlog
  
  validates :email, uniqueness: true
  
  has_many :usershops, dependent: :destroy
  has_many :shops, through: :usershops
  has_many :lockdays
  has_many :orders
  has_many :orderlogs
  


    private
        # ensure that there are no orders referencing this user
        def ensure_not_referenced_by_any_order_or_orderlog
            unless orders.empty?
                errors.add(:base, 'Cannot destroy - orders present for this user')
                throw :abort
            end
            unless orderlogs.empty?
                errors.add(:base, 'Cannot destroy - orderlog entries present for this user')
                throw :abort
            end            
        end
end

app/models/usershop.rb
class Usershop < ApplicationRecord
  belongs_to :user
  belongs_to :shop
  
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    respond_to do |format|
      if @ingredient.destroy
        format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
        format.json { head :no_content }
      else
        if @ingredient.errors.any?
          @notice_message = "prohibited this ingredient from being destroyed"
          @ingredient.errors.full_messages.each do |message|
            @notice_message += ": " + message
          end
        end
        format.html { redirect_to ingredients_url, notice: @notice_message  }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:item, :unit)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/lockdays_helper.rb
module LockdaysHelper
end

app/helpers/orderlogs_helper.rb
module OrderlogsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usershops_helper.rb
module UsershopsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(ingredient) do |f| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %>
    <%= f.text_field :item %>
  </div>

  <div class="field">
    <%= f.label :unit %>
    <%= f.text_field :unit %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.item %></td>
        <td><%= ingredient.unit %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>
<br>
<%= link_to 'Show recipes', recipes_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @ingredient.item %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @ingredient.unit %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>