config/routes.rb
Rails.application.routes.draw do
  resources :usershops
  resources :sectors
  get 'orderlogdayshop', to: 'orderlogs#indexdayshop'
  resources :orderlogs, :only => [:create, :index]
  resources :recipes
  resources :ingredients
  post 'locktoday', to: 'lockdays#locktoday'
  resources :lockdays, :only => [:index, :new, :create, :destroy]
  get 'reports/baker'
  get 'reports/deliver'

  get 'ordersedit', to: 'orders#indexedit'
  post 'orders/:id', to: 'orders#update'
  get 'ordersproductshops', to: 'orders#productshop'
  get 'ordersbakers', to: 'orders#bakers'
  get 'ordersbakerdoes', to: 'orders#bakerdoes'
  get 'ordersdelivery', to: 'orders#delivery'
  get 'ordersdeliverypdf', to: 'orders#deliverypdf'
  get 'downloadorders', to: 'orders#downloadorders'
  #get 'ordersbakers/:day', to: 'orders#bakers'
  #get 'ordersdelivery/:day', to: 'orders#delivery'
  resources :orders
  #get 'sessions/new'
  #get 'sessions/create'
  #get 'sessions/destroy'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end
  
  post 'userdayshop(/:id)', to: 'users#updatedayshop'
  patch 'userdayshop(/:id)', to: 'users#updatedayshop'
  get 'userdayshop', to: 'users#editdayshop'
  resources :users
  resources :shops,  :except => [:destroy]
  get 'displayproducts', to: 'products#display'
  resources :products, :except => [:destroy]
  
  root 'orders#indexedit'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :shop
  belongs_to :user
  
  def self.dayshop(day, shop_id)
    where("day = ? and shop_id = ?", day, shop_id)
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  ###before_action :check_login
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /productshop
  def productshop
    @prodshop = Order.find_by_sql ["
      SELECT o.id, p.title, s.name, o.quantity, p.price, o.cost
      FROM orders AS o
      INNER JOIN products AS p ON o.product_id = p.id AND o.day = ?
      INNER JOIN shops AS s ON o.shop_id = s.id
    ", @current_day]
    #logger.debug "@prodshop: " + @prodshop.inspect 

    @colheaders = Order.find_by_sql ["
      SELECT DISTINCT ON (s.name) o.id, s.name, o.shop_id
      FROM orders AS o
      INNER JOIN shops AS s 
      ON o.shop_id = s.id AND o.day = ?
      ORDER BY s.name ASC
    ", @current_day]
    #logger.debug "@colheaders: " + @colheaders.inspect 

    ###@rowheaders_keep = Order.find_by_sql ["
    ###  SELECT DISTINCT ON (p.title) p.title, o.id, o.product_id, p.sector_id
    ###  FROM orders AS o
    ###  INNER JOIN products AS p 
    ###  ON o.product_id = p.id AND o.day = ?
    ###  ORDER BY p.title ASC
    ###", @current_day]

    @rowheaders = Order.find_by_sql ["
      SELECT DISTINCT ON (p.title) p.title, o.id, o.product_id, p.sector_id, s.name
      FROM orders AS o
      INNER JOIN products AS p ON o.product_id = p.id AND o.day = ?
      INNER JOIN sectors AS s ON s.id = p.sector_id
      ORDER BY p.title ASC
    ", @current_day]
    #logger.debug "@rowheaders: " + @rowheaders.inspect 

    @summary = Array.new(2 + @rowheaders.count){Array.new(3 + @colheaders.count){Hash.new()}}

    i = 1
    @rowindex = Hash.new
    @rowheaders.sort_by(&:name).each do |entry|
      i += 1
      thisproduct=entry.title
      @summary[i][2]["value"] = 0
      @summary[i][0]["value"] = entry.name.to_str 
      @summary[i][1]["value"] = thisproduct 
      @rowindex[thisproduct] = i
    end
    #logger.debug "@rowindex: " + @rowindex.inspect
    
    j = 2
    @colindex = Hash.new
    @colheaders.each do |entry|
      j += 1
      thisshop=entry.name
      @summary[1][j]["value"] = 0
      @summary[0][j]["value"] = thisshop
      @colindex[thisshop] = j
    end
    #logger.debug "@colindex: " + @colindex.inspect
    
    #misc headers
    @summary[1][2]["value"] = "Totals"
    @summary[1][0]["value"] = "Category"
    @summary[1][1]["value"] = "Products"
    @summary[0][3]["value"] = "Shops"
    
    @prodshop.each do |entry|
      thisprod = entry.title    #row - i
      thisshop = entry.name     #col - j
      @summary[@rowindex[thisprod]][@colindex[thisshop]]["value"]   = entry.quantity
      unless entry.cost.nil?    # if has not been locked yet, treat as 0 value.
        @summary[1][@colindex[thisshop]]["value"] += entry.quantity * entry.cost          #was price for product price, now from order table
      end
      @summary[@rowindex[thisprod]][2]["value"] += entry.quantity
    end
    j=2
    # format the currency cells
    @colheaders.each do |entry|
      j += 1
      @summary[1][j]["value"] = "$" + sprintf("%.2f", @summary[1][j]["value"])
    end
    
    #logger.debug "@summary: " + @summary.inspect
  end


  # GET /bakers
  def bakers
    #logger.debug "bakers:" + @bakers.inspect
    @bakers = Order.find_by_sql ["
      SELECT SUM(quantity) as totalqty, p.title, s.name
      FROM orders AS o
      INNER JOIN products AS p ON o.product_id = p.id AND o.day = ?
      INNER JOIN sectors AS s ON p.sector_id = s.id
      GROUP BY s.name, p.title
      ORDER BY s.name ASC, p.title ASC
    ", @current_day]
    #logger.debug "@bakers: " + @bakers.inspect    
    ###@baker1 = Order
    ###          .where("day = ?", params[:day])
    ###          .joins(:product, :shop)
    ###          .order(:product_id)
              
    @lockday = Lockday
                 .where("day = ?", params[:day])
              
    #logger.debug "lockday:" + @lockday.inspect
  end

 # GET /bakerdoes
  def bakerdoes
    @bakerdoes = Order.find_by_sql ["
      SELECT sum(quantity * r.amount) as totalqty, i.item, i.unit
      FROM orders AS o
      INNER JOIN products AS p ON o.product_id = p.id AND o.day = ?
      INNER JOIN recipes AS r ON p.id = r.product_id
      INNER JOIN ingredients AS i ON r.ingredient_id = i.id
      GROUP BY i.item, i.unit
    ", @current_day]
  end

  # GET /delivery
  def delivery
    @bakery = Shop.find(1)
    bakeryAddress = @bakery.address
    logger.debug("@bakery: " + @bakery.inspect)
    @bakeryA = bakeryAddress.split(",")
    logger.debug("@bakeryA: " + @bakeryA.inspect)
    @delivery = Order.find_by_sql ["
      SELECT o.id, o.quantity, p.title, s.name as shop_name, o.shop_id, c.name as sector_name
      FROM orders AS o
      INNER JOIN products AS p ON o.product_id = p.id AND o.day = ?
      INNER JOIN shops AS s ON o.shop_id = s.id
      INNER JOIN sectors AS c ON c.id = p.sector_id
      ORDER BY s.name ASC, p.title ASC
    ", @current_day]
    logger.debug("@delivery: " + @delivery.inspect)
  end

  # GET /deliverypdf
  def deliverypdf
    @bakery = Shop.find(1)
    bakeryA = @bakery.address
    @bakeryA = bakeryA.split(",")
    logger.debug("@bakeryA: " + @bakeryA.inspect)
    logger.debug("@bakery: " + @bakery.inspect)
    @delivery = Order.find_by_sql ["
      SELECT o.id, o.quantity, p.title, s.name as shop_name, o.shop_id, c.name as sector_name
      FROM orders AS o
      INNER JOIN products AS p ON o.product_id = p.id AND o.day = ?
      INNER JOIN shops AS s ON o.shop_id = s.id
      INNER JOIN sectors AS c ON c.id = p.sector_id      
      ORDER BY s.name ASC, p.title ASC
    ", @current_day]
    logger.debug("@delivery: " + @delivery.inspect)    
    respond_to do |format|
      format.html do
        render pdf: "Delivery_Dockets",
                    layout: "layouts/pdf.html.erb",
                    template: "orders/deliverypdf.pdf.erb",
                    locals: {:delivery => @delivery}#,
                    #show_as_html: true
      end
    end
  end

  # GET /ordersedit
  def indexedit
  # stuff required for the user update of day and shops
  #logger.debug "current_user_id:" + @current_user_id.inspect
  @user = User.find(@current_user_id)
  #logger.debug "@user:" + @user.inspect
  @shop_options = get_shop_options
  #logger.debug "@shop_options: " + @shop_options.inspect
  # first up - check if there are already orders for this day
  # if not, give the user a chance to clone from an existing order
    @orders = Order.all
    .where("day = ? AND shop_id = ?", @current_day, @current_shop_id)
    if @orders.empty?                     # there are no orders for this day
      @noorders = true
      @copy_from_day = params[:copyfrom]
      unless @copy_from_day.blank?        # parameters has provided a day to copy from
        @orders_from = Order
                       .where("day =? AND shop_id = ?", @copy_from_day, @current_shop_id)
        if @orders_from.empty?         # make sure there is somethign to copy
          @noorders = true
          @copymessage = "You tried to copy from a day (" + @copy_from_day + ") that has no orders!!!"
        else                          # now proceed with the copy
          # determine fields for updating - copied orders and logging
          logfields = Hash.new
          logfields[:day] = @current_day
          logfields[:user_id] = @current_user_id
          logfields[:shop_id] = @current_shop_id
          @orders_from.each do |order|
            @order_new = Order.new(logfields)
            @order_new.product_id = order.product_id
            @order_new.quantity = order.quantity
            @order_new.locked = false
            @order_new.save
            # now for the audit log on the Order updates, creates and deletes
            @log = Orderlog.new(logfields)
            @log.product_id = order.product_id
            @log.quantity = order.quantity
            @log.oldquantity = 0
            @log.save
          end
          @noorders = false           # orders now present for today
        end
      end
    else
      @noorders = false
    end
    
    # We now process the normal display for ordering information.
    # Above this was simply detecting if this order was empty and what action to take.
    @products = Product.find_by_sql [ "
      SELECT p.id as product_id, p.title, p.description, p.leadtime, p.price, p.inactive, o.id as order_id, o.quantity, o.shop_id, o.day, o.locked, o.user_id, s.name as sector_name, o.cost
      FROM products AS p
      LEFT OUTER JOIN orders AS o ON p.id = o.product_id AND o.day = ? AND o.shop_id = ?
      INNER JOIN sectors AS s ON p.sector_id = s.id 
      WHERE p.inactive = false
      ORDER BY s.name, p.title
    ", @current_day, @current_shop_id ]
    
    ###logger.debug "@products: " + @products.inspect

    # Locked order items and days needs to be passed into the view simply.
    # The lock attribute on the ordered product is set here but never saved.
    # This order attribute is then used to determine if the view locks the 
    # quantity field - so that it cannot be changed in the view.
    #
    # check if this day has been locked by the baker
    # shown by the delivery day being added to the locked table
    @locked = Lockday
             .where("day = ?", @current_day)
             .count
    if @locked > 0
      # So lock all the products in this order
      @products.each do |p|  
        p.locked = true
      end
    elsif ["baker", "owner"].include? @current_role 
      # baker can overide individual locking limits based on time (but not if day is locked).
      # do nothing - all enteries are already false   
    else
      # check if individual products need to be locked based on time of week.
      # Need to now do some work to see if any ordere products for today should be locked
      # Need to reference midnight as the start of delivery day being processed.
      timedeliveryday = @current_day.to_time                  # epoch time of the currnt day at midnight

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.text_field :product_id %>
  </div>

  <div class="field">
    <%= f.label :shop_id %>
    <%= f.text_field :shop_id %>
  </div>

  <div class="field">
    <%= f.label :day %>
    <%= f.date_select :day %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :locked %>
    <%= f.check_box :locked %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/bakerdoes.html.erb
<p id="notice"><%= notice %></p>

<h3>Dough required to fill the Orders for delivery on : <%= Date.parse(@current_day).strftime("%A %d %B %Y") %></h3>

<table>
  <thead>
    <tr>
      <th>Ingredient</th>
      <th>Quantity</th>
      <th>Units</th>
    </tr>
  </thead>

  <tbody>
    <% @bakerdoes.each do |bakerdoe| %>
      <tr>
        <td><%= bakerdoe.item %></td>
        <td><%= bakerdoe.totalqty %></td>
        <td><%= bakerdoe.unit %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/bakers.html.erb
<p id="notice"><%= notice %></p>

<h3>Bake to fill the Orders for delivery on : <%= Date.parse(@current_day).strftime("%A %d %B %Y") %></h3>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Product</th>
      <th>Quantity</th>
    </tr>
  </thead>

  <tbody>
    <% @bakers.each do |baker| %>
      <tr>
        <td><%= baker.name %></td>
        <td><%= baker.title %></td>
        <td><%= baker.totalqty %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/delifvery.html.erb
<p id="notice"><%= notice %></p>

<h1>Deliveries for : <%= @current_day %> (<%= Date.parse(@current_day).strftime("%A") %>)</h1>

<h2></h2><%= link_to 'PDF Version', ordersdeliverypdf_path %></h2>

<% @previous_shop = "" %>
<% @delivery.each do |deliver| %>
  
  <% if @previous_shop != deliver.shop_name %>
    <% if @previous_shop != "" %>
        </tbody>
      </table>
    <% end %>
    <% @previous_shop = deliver.shop_name %>
    <p>
    <h2>Deliveries to <%= deliver.shop_name %> for <%= Date.parse(@current_day).strftime("%A") %> <%= @current_day %> </h2>
      <table>
        <thead>
          <tr>
            <th>Product</th>
            <th>Quantity</th>
          </tr>
        </thead>
        <tbody>
  <% end %>
  
  <tr>
    <td><%= deliver.title %></td>
    <td><%= deliver.quantity %></td>
  </tr>
<% end %>
  </tbody>
</table>

<br>
<%= link_to 'Show bakers page', ordersbakers_path %>
<%= link_to 'Show baker does page', ordersbakerdoes_path %>
<%= link_to 'Show product shop summary page', ordersproductshops_path %>
<%= link_to 'Order editing for shop on delivery day', ordersedit_path %>
<%= link_to 'Show ingredients', ingredients_path %>
<%= link_to 'Show recipes', recipes_path %>

app/views/orders/deliverypdf.html.erb
<p id="notice"><%= notice %></p>

<h1>Deliveries for : <%= @current_day %> (<%= Date.parse(@current_day).strftime("%A") %>)</h1>

<% @previous_shop = "" %>
<% @delivery.each do |deliver| %>
  
  <% if @previous_shop != deliver.shop_name %>
    <% if @previous_shop != "" %>
        </tbody>
      </table>
    <% end %>
    <% @previous_shop = deliver.shop_name %>
    <p>
    <h2>Deliveries to <%= deliver.shop_name %> for <%= Date.parse(@current_day).strftime("%A") %> <%= @current_day %> </h2>
      <table>
        <thead>
          <tr>
            <th>Product</th>
            <th>Quantity</th>
          </tr>
        </thead>
        <tbody>
  <% end %>
  
  <tr>
    <td><%= deliver.title %></td>
    <td><%= deliver.quantity %></td>
  </tr>
<% end %>
  </tbody>
</table>

<br>
<%= link_to 'Show bakers page', ordersbakers_path %>
<%= link_to 'Show baker does page', ordersbakerdoes_path %>
<%= link_to 'Order editing for shop on delivery day', ordersedit_path %>

app/views/orders/deliverypdf.pdf.20170629.erb
<h1>Deliveries for : <%= @current_day %> (<%= Date.parse(@current_day).strftime("%A") %>)</h1>
<p style='page-break-after:always;'></p>

<% @previous_shop = "" %>
<% @delivery.each do |deliver| %>
  
  <% if @previous_shop != deliver.shop_name %>
    <% if @previous_shop != "" %>
        </tbody>
      </table>
      <p style='page-break-after:always;'></p>
    <% end %>
    <% @previous_shop = deliver.shop_name %>
    <p>
    <h2>Deliveries to <%= deliver.shop_name %> for <%= Date.parse(@current_day).strftime("%A") %> <%= @current_day %> </h2>
      <table>
        <thead>
          <tr>
            <th>Product</th>
            <th>Quantity</th>
          </tr>
        </thead>
        <tbody>
  <% end %>
  
  <tr>
    <td><%= deliver.title %></td>
    <td><%= deliver.quantity %></td>
  </tr>
<% end %>
  </tbody>
</table>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>
user: <%= @current_user %><br>
shop: <%= @current_shop %> - (<%= @current_shop_id %>)<br>
day : <%= @current_day %><br>
shop_id : <%= @current_shop_id %><br>

<p><%= link_to 'Download all orders', downloadorders_path %></p>

<table>
  <thead>
    <tr>
      <th>Order_id</th>
      <th>Product</th>
      <th>Shop</th>
      <th>Day</th>
      <th>Quantity</th>
      <th>Locked</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.product_title %></td>
        <td><%= order.shop_name %></td>
        <td><%= order.day %></td>
        <td><%= order.quantity %></td>
        <td><%= order.locked %></td>
        <td><%= order.user_name %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Order editing for shop on delivery day', ordersedit_path %>
<br>
<%= link_to 'Show bakers page', ordersbakers_path %>
<%= link_to 'Show delivery page', ordersdelivery_path %>
<%= link_to 'Download all orders', downloadorders_path %>

app/views/orders/indexedit.html.erb
<p id="notice"><%= notice %></p>

<div class="info-container">
  <div class="info-wrapper">
    <h1 class="main">Order Details</h1>
    <% user = @user %>
    <%= form_for(user, :url => userdayshop_path, method: :patch) do |f| %>
    
      <div class="field">
        <%= f.text_field :id, {hidden: true, id: "user_id" } %>
        <% logger.debug "in form - @current_user_id: " + @current_user_id.inspect %>
      </div>
      
      <div class="field-wrapper">
        <div class="field intro">
          <%= @user.name %>
        </div>
        
        <div class="field">
          <input type="date" class="auto-submit-item" id="day" name="user[day]" value="<%= user.day %>">
          <% if @locked > 0 %>
            Locked
          <% else %>
            <% if ["baker", "owner", "root"].include? @current_role %>
              <%= link_to 'Lock today', locktoday_path, { method: :post, :confirm => "Are you sure?" } %>
            <% end %>
          <% end %>          
        </div>
      
        <div class="field">
          <%= f.select :shop, @shop_options, {}, {:class => 'auto-submit-item', :id => 'shop'} %>
        </div>
        
        <div class="hidden_content", id="shop_id">
          <%=  @current_shop_id %>
        </div>
      
        <div class="actions">
          <%= f.submit %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<% unless @locked > 0 %>
  <% if @noorders == true %>
    <div class=checkordersempty>
      <form action=<%= ordersedit_path %> method="get" >
        <% if @copymessage.nil? %>
          <h2>Do you want to copy a previous order to start off - select the day and click copy?</h2>
        <% else %>
          <h2><%= @copymessage %></h2>
        <% end %>
        Copy Order from:<input type="date" name="copyfrom"><br>
        Copy  Order  to:<input type="date" value=<%= @current_day %> name="copyto" readonly><br>
        <button type="submit" value="Submit">Copy</button>
        <button class="noclonebutton" type="button" value="Button" >No Thanks</button>
      </form>
      <br>
    </div>
  <% end %>
<% end %>

  <% cat = "" %>
  <% @products.each do |product| %>
    <% if product.sector_name != cat %>
      <% unless cat.blank? %>
        </table></div>
      <% end %>
      <% cat = product.sector_name %>
      <div class="sector"><b><%= cat %><span> - </span></b></div>
      <div>
      <table class="product_group, showme fixed_table">
    <% end %>
    <tr class="product" id="<%= product.product_id %>">
      <td class="product_id"><%= product.product_id %></td>
      <td class="title"><%= product.title %></td>
      <% if product.locked? %>
        <td class="qty_locked"><%= product.quantity %></td>
      <% else %>
        <td>
          <input class="qty" type="number" pattern="[0-9]*] id="<%= product.order_id.to_i %>" value="<%= product.quantity %>" min=0 />
          <p class="origqty"><%= product.quantity =%></p>
        </td>
      <% end %>
      <td class="order_id"><%= product.order_id %></td>
    </tr>
  <% end %>
  <% unless cat.blank? %>
    </table>
  <% end %>

app/views/orders/indexedit_backup.html.erb
<p id="notice"><%= notice %></p>

<table>
  <tr><td>user</td><td><%= @current_user %></td><td id="user_id"><%= @current_user_id %></td></tr>
  <tr><td>shop</td><td><%= @current_shop %></td><td id="shop_id"><%= @current_shop_id %></td></tr>
  <tr><td>deliver</td><td id="day"><%= @current_day %> (<%= Date.parse(@current_day).strftime("%A") %>)</td><td></td></tr>
</table>
<%= link_to 'Update shop or delivery day', userdayshop_path %>

<h1>Order for Products - index_edit</h1>

<% if @noorders == true then %>
  <div class=checkordersempty>
    <form action=<%= ordersedit_path %> method="get" >
      <% if @copymessage.nil? %>
        <h2>do you want to copy a previous order to start off - select the day and click copy?</h2>
      <% else %>
        <h2><%= @copymessage %></h2>
      <% end %>
      Copy Order from:<input type="date" name="copyfrom"><br>
      Copy  Order  to:<input type="date" value=<%= @current_day %> name="copyto" readonly><br>
      <button type="submit" value="Submit">Copy</button>
      <button class="noclonebutton" type="button" value="Button" >No Thanks</button>
    </form>
    <br>
  </div>
<% end %>

<table>
  <% @products.each do |product| %>
    <tr class="product" id="<%= product.product_id %>">
      <td class="product_sector_name"><%= product.sector_name %></td>
      <td class="product_id"><%= product.product_id %></td>
      <td class="title"><%= product.title %></td>
      <td class="price"><%= number_to_currency(product.price) %></td>
      <% if @locked == 0 %>
        <td> 
          <input class="qty" type="number" id="<%= product.order_id %>" value="<%= product.quantity %>" min=0 />
          <p class="origqty"><%= product.quantity =%></p>
        </td>
      <% else %>
        <td class="qty_locked"><%= product.quantity %></td>
      <% end %>
      <td class="order_id"><%= product.order_id %></td>
    </tr>
  <% end %>
</table>

<br>

<%= link_to 'Show all Orders', orders_path %>
<%= link_to 'Show bakers page', ordersbakers_path %>
<%= link_to 'Show bakers doe page', ordersbakerdoes_path %>
<%= link_to 'Show delivery page', ordersdelivery_path %>
<%= link_to 'Show product shop summary page', ordersproductshops_path %>
<%= link_to 'Show order logs', orderlogdayshop_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/productshop.html.erb
<p id="notice"><%= notice %></p>

<h3>Products by Shops Summary of Orders for delivery on: <%=  Date.parse(@current_day).strftime("%A %d %B %Y") %></h3>

<table>
  <% i = 0 %>
  <% @summary.each do |rows| %>
    <tr>
    <% rows.each do |cells| %>
      <td>
        <% if cells.key?("value") then %>
          <%= cells["value"].to_s %>
        <% end %>
      </td>
    <% end %>
    </tr>
  <% end %>
</table>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @order.product %>
</p>

<p>
  <strong>Shop:</strong>
  <%= @order.shop %>
</p>

<p>
  <strong>Day:</strong>
  <%= @order.day %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order.quantity %>
</p>

<p>
  <strong>Locked:</strong>
  <%= @order.locked %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>