config/routes.rb
Rails.application.routes.draw do
  resources :usershops
  resources :sectors
  get 'orderlogdayshop', to: 'orderlogs#indexdayshop'
  resources :orderlogs, :only => [:create, :index]
  resources :recipes
  resources :ingredients
  post 'locktoday', to: 'lockdays#locktoday'
  resources :lockdays, :only => [:index, :new, :create, :destroy]
  get 'reports/baker'
  get 'reports/deliver'

  get 'ordersedit', to: 'orders#indexedit'
  post 'orders/:id', to: 'orders#update'
  get 'ordersproductshops', to: 'orders#productshop'
  get 'ordersbakers', to: 'orders#bakers'
  get 'ordersbakerdoes', to: 'orders#bakerdoes'
  get 'ordersdelivery', to: 'orders#delivery'
  get 'ordersdeliverypdf', to: 'orders#deliverypdf'
  get 'downloadorders', to: 'orders#downloadorders'
  #get 'ordersbakers/:day', to: 'orders#bakers'
  #get 'ordersdelivery/:day', to: 'orders#delivery'
  resources :orders
  #get 'sessions/new'
  #get 'sessions/create'
  #get 'sessions/destroy'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end
  
  post 'userdayshop(/:id)', to: 'users#updatedayshop'
  patch 'userdayshop(/:id)', to: 'users#updatedayshop'
  get 'userdayshop', to: 'users#editdayshop'
  resources :users
  resources :shops,  :except => [:destroy]
  get 'displayproducts', to: 'products#display'
  resources :products, :except => [:destroy]
  
  root 'orders#indexedit'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    validates :item, :unit, presence: true
    validates :item, uniqueness: true
    
    has_many :recipes
    has_many :products, through: :recipes
    
    before_destroy :ensure_not_referenced_by_any_recipe

    private
        # ensure that there are no recipes referencing this ingredient
        def ensure_not_referenced_by_any_recipe
            unless recipes.empty?
                errors.add(:base, ' - recipes present for this ingredient')
                throw :abort
            end
        end
end

app/models/lockday.rb
class Lockday < ApplicationRecord
    validates :day, uniqueness: true
    
    belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :shop
  belongs_to :user
  
  def self.dayshop(day, shop_id)
    where("day = ? and shop_id = ?", day, shop_id)
  end
  
end

app/models/orderlog.rb
class Orderlog < ApplicationRecord
    belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
    validates :title, presence: true
    validates :price, numericality: {greater_than_or_equal_to: 0.01}
    validates :title, uniqueness: true
    
    has_many :orders
    has_many :shops, through: :orders
    has_many :recipes
    has_many :ingredients, through: :recipes
    belongs_to :sector
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :product
  belongs_to :ingredient
end

app/models/sector.rb
class Sector < ApplicationRecord
    has_many :products 
    before_destroy :ensure_not_referenced_by_any_product

    private
        # ensure that there are no products referencing this sector
        def ensure_not_referenced_by_any_product
            unless products.empty?
                errors.add(:base, 'Cannot destroy - products present for this sector')
                throw :abort
            end
        end
end

app/models/shop.rb
class Shop < ApplicationRecord
    validates :name, :contact, :phone, :email, presence: true
    validates :name, uniqueness: true
    
    has_many :orders
    has_many :products, through: :orders
    
    has_many :usershops
    has_many :users, through: :usershops
    
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_destroy :ensure_not_referenced_by_any_order_or_orderlog
  
  validates :email, uniqueness: true
  
  has_many :usershops, dependent: :destroy
  has_many :shops, through: :usershops
  has_many :lockdays
  has_many :orders
  has_many :orderlogs
  


    private
        # ensure that there are no orders referencing this user
        def ensure_not_referenced_by_any_order_or_orderlog
            unless orders.empty?
                errors.add(:base, 'Cannot destroy - orders present for this user')
                throw :abort
            end
            unless orderlogs.empty?
                errors.add(:base, 'Cannot destroy - orderlog entries present for this user')
                throw :abort
            end            
        end
end

app/models/usershop.rb
class Usershop < ApplicationRecord
  belongs_to :user
  belongs_to :shop
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  #skip_before_action :authorise

  # GET /displayproducts
  def display
    #@products = Product.includes(:sector).all
    #            .order("sectors.name, title")
                
    @products = Product.find_by_sql [ "
      SELECT p.id as product_id, p.title, p.description, p.leadtime, p.price, p.inactive, s.name as sector_name
      FROM products AS p
      INNER JOIN sectors AS s ON p.sector_id = s.id and p.inactive = FALSE
      ORDER BY s.name, p.title
    "]
    logger.debug "@products: " + @products.inspect
  end

  # GET /products
  # GET /products.json
  def index
    logger.debug "in products controller - index action"
    #@products = Product.all
    #            .order("title")
    @products = Product.includes(:sector).all
                .order("sectors.name, title")
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @sector_options = Sector.all.map{ |u| [u.name, u.id] }
  end

  # GET /products/1/edit
  def edit
    @sector_options = Sector.all.map{ |u| [u.name, u.id] }
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  # never what a product destroyed as it it linked to the orders
  # Can inactive through the edit panel.
  ###def destroy
  ###  @product.destroy
  ###  respond_to do |format|
  ###    format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
  ###    format.json { head :no_content }
  ###  end
  ###end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :leadtime, :price, :sector_id, :sector, :inactive)
    end
end

app/helpers/lockdays_helper.rb
module LockdaysHelper
end

app/helpers/orderlogs_helper.rb
module OrderlogsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usershops_helper.rb
module UsershopsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :sector_id %>
    <%= f.select :sector_id, @sector_options %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 10, cols: 60 %>
  </div>

  <div class="field">
    <%= f.label :leadtime %>
    <%= f.number_field :leadtime %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :inactive %>
    <%= f.check_box :inactive %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/display.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

  <% cat = "" %>
  <% @products.each do |product| %>
    <% if product.sector_name != cat %>
      <% unless cat.blank? %>
        </table>
      <% end %>
      <% cat = product.sector_name %>
      <div class="sector"><b><%= cat %></b></div>
      <table class="product_group, showme">
    <% end %>      
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td class="list_description">
        <dl>
          <dt><%= product.title %></dt>
          <dd><%= truncate(strip_tags(product.description), length: 80) %></dd>
        </dl>
      </td>
      <td><%= product.leadtime %></td>
      <td class="price"><%= number_to_currency(product.price) %></td>
    </tr>
  <% end %>
  <% unless cat.blank? %>
    </table>
  <% end %>

<br />

<%= link_to 'Place Orders', ordersedit_path %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <% @products.each do |product| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td class="list_description">
        <dl>
          <dt><%= product.title %></dt>
          <dd><%= truncate(strip_tags(product.description), length: 80) %></dd>
        </dl>
      </td>
      <td><%= product.sector.name %></td>
      <td><%= product.leadtime %></td>
      <td>
      <% if product.inactive %>
        Inactive
      <% else %>
        Active
      <% end %>
      </td>
      <td class="price"><%= number_to_currency(product.price) %></td>
        
      <td class="list_actions">
        <%= link_to 'Edit', edit_product_path(product) %><br/>
      </td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>
<%= link_to 'Customer View of Products', displayproducts_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Leadtime:</strong>
  <%= @product.leadtime %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>